version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306:3306"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: sj26/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
